{% set version = "0.2.1" %}

package:
  name: pymt_permamodel
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_permamodel/archive/v{{ version }}.tar.gz
  sha256: 2f90e539963d2e3cef341121bbbaa9634ab240cc9d0021bf719a692b9f555694

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - model_metadata
  run:
    - python >=3.9
    - permamodel

test:
  imports:
    - pymt_permamodel

about:
  home: https://github.com/pymt-lab/pymt_permamodel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the permamodel BMI.
  dev_url: https://github.com/pymt-lab/pymt_permamodel

extra:
  recipe-maintainers:
    - mdpiper
    - mcflugen
