{% set version = "0.2.3" %}
{% set python_min = python_min|default("3.10") %}

package:
  name: pymt_permamodel
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_permamodel/archive/v{{ version }}.tar.gz
  sha256: 46b0e75a53dbb0800aaaa3c709e6fd5774923babdc9cc094a9ffaaeb7d23247f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
    - model_metadata
  run:
    - python >={{ python_min }}
    - permamodel

test:
  requires:
    - python ={{ python_min }}
  imports:
    - pymt_permamodel

about:
  home: https://github.com/pymt-lab/pymt_permamodel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the permamodel BMI.
  dev_url: https://github.com/pymt-lab/pymt_permamodel

extra:
  recipe-maintainers:
    - mdpiper
    - mcflugen
