{% set version = "0.2" %}

package:
  name: pymt_permamodel
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_permamodel/archive/v{{ version }}.tar.gz
  sha256: 81eac98df42fb7e732a34fdc7de0608d73d7915994036b1e4a796dd711f76e60

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
    - model_metadata
  run:
    - python
    - permamodel

test:
  imports:
    - pymt_permamodel

about:
  home: https://github.com/mcflugen/pymt_permamodel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the permamodel BMI.
  dev_url: https://github.com/mcflugen/pymt_permamodel

extra:
  recipe-maintainers:
    - mcflugen
