{% set version = "0.2.3" %}
{% set python_min = python_min|default("3.10") %}

package:
  name: pymt_permamodel
  version: {{ version }}

source:
  url: https://github.com/pymt-lab/pymt_permamodel/archive/v{{ version }}.tar.gz
  sha256: 46b0e75a53dbb0800aaaa3c709e6fd5774923babdc9cc094a9ffaaeb7d23247f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
    - model_metadata
  run:
    - python >={{ python_min }}
    - permamodel

test:
  requires:
    - python ={{ python_min }}
    - bmi-tester
  imports:
    - pymt_permamodel
  source_files:
    - examples
  commands:
    - bmi-test pymt_permamodel.bmi:FrostNumber --config-file=${PWD}/examples/Frostnumber_example_singlesite_singleyear.cfg --root-dir=examples -vvv  # [unix]
    - bmi-test pymt_permamodel.bmi:Ku --config-file=${PWD}/examples/Ku_method.cfg --root-dir=examples -vvv  # [unix]
    - bmi-test pymt_permamodel.bmi:KuEnhanced --config-file=${PWD}/examples/Ku_bmi_example_config.toml --root-dir=examples -vvv  # [unix]

about:
  home: https://github.com/pymt-lab/pymt_permamodel
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python package that wraps the permamodel BMI.
  dev_url: https://github.com/pymt-lab/pymt_permamodel

extra:
  recipe-maintainers:
    - mdpiper
    - mcflugen
